name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and tag Docker image
      - name: Build Docker image
        run: |
          docker build -t gabisorici1/devopsautomation:latest .

      # Push Docker image to DockerHub
      - name: Push Docker image
        run: |
          docker push gabisorici1/devopsautomation:latest
